services:
  - type: web
    name: nautilus-banking-api
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: PUBLIC_KEY
        sync: false
      - key: HMAC_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
